### ISSUE TITLE
同一个邮箱不能使用github登录

### ISSUE THREAD

**Issue by rylandong** [b3log/baidu-netdisk-downloaderx#11]
1.使用aaa@test.com注册了黑客派。
2.使用aaa@test.com注册了github.
3.在BND关联github，就会报截图中的错，显示邮箱重复。
4.卡在了图片中的步骤无法更换账户或者进入下一步。
![qq 20180927131729](https://user-images.githubusercontent.com/43604039/46124812-a66ef400-c258-11e8-8b51-5a81824708b4.png)

**Comment by 88250** [comment]
在黑客派 - 设置 - 账号 中绑定 GitHub 即可。
