### ISSUE TITLE
BND2下载一段时间之后，下载速度变成0，而且有许多未知错误

### ISSUE THREAD

**Issue by hlsc1989** [b3log/baidu-netdisk-downloaderx#13]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/bnd)搜寻资料解决问题。

----

### 描述问题

BND2下载一段时间之后，有许多未知错误，最终所有的下载文件下载速度变成0
### 重现步骤

请描述如何重现这个问题：

1. 选择下载文件夹，不是单文件下载
2. 点击下载

### 期待的结果

全部下载成功

### 截屏或录像

被删掉了

### 桌面端环境

win10

**Comment by 88250** [comment]
可能是账号被限制了，这个暂时无解。

**Comment by steven1227** [comment]
限制多久大概知道吗？不会一直不行了吧。。 @88250

**Comment by 88250** [comment]
不要用任何第三方下载器，一两天后会恢复。 @steven1227

**Comment by 1step2hell** [comment]
遇到同样的情况，感觉跟账号没关系，同样的资源，同样的账号，BND1可以下，BND2未知错误。

**Comment by 1step2hell** [comment]
补充下情况，mac 10.14.5，BND1 v4.0.0， BND2 v2.0.0，BND2下载直接未知错误。
从现象来说感觉是BND2代码有问题，建议客户端显示具体错误代码，用户上报可以反馈具体错误代码方便排查。

**Comment by 1step2hell** [comment]
再更新下：
* BND1 偶尔出现无法启动
* BND1 关闭后重新打开，上次下载未完成的文件 在重开后缓冲为0字节大小，然后提示下载完成。整个下载目录删了重下也没用，应该是哪里有配置记录上次的下载，没找着。

感觉坑还是很多，目前试过pan-light、BND，都不怎么理想，放弃了。
希望能做得更好，过段时间再来尝试。

**Comment by 88250** [comment]
@1step2hell 感谢反馈！

Mac 下面 BND1 确实会出现无法启动的情况，这个问题一直存在而且没法定位。尝试多次重启可能可以解决。其他问题可能较难定位，暂时先继续观察并等待其他用户反馈。
