### ISSUE TITLE
能不能编译个ARM64用的版本，这样可以跑在路由器或是树莓牌之类的arm设备上，谢谢

### ISSUE THREAD

**Issue by fwnl** [b3log/baidu-netdisk-downloaderx#14]
能不能编译个ARM64用的版本，这样可以跑在路由器或是树莓牌之类的arm设备上，谢谢

**Comment by 88250** [comment]
这个不支持，因为用了 aria2，你的场景可以试试 https://github.com/iikira/BaiduPCS-Go
