### ISSUE TITLE
 下载文件失败，没有出现下载进度，直接瞬间显示下载成功， 但是实际数据为0byte.

### ISSUE THREAD

**Issue by steven1227** [b3log/baidu-netdisk-downloaderx#18]
----

### 描述问题

下载文件失败，没有出现下载进度，直接瞬间显示下载成功， 但是实际数据为0byte.
前两天用过还是可以使用的。

### 桌面端环境

- OS: [ linux ubuntu18.04]
- Browser [chrome]

**Comment by 88250** [comment]
1. 和下载的资源有关
2. 可能是百度云账号被限制了，过一两天再试试

**Comment by sdsy888** [comment]
> 1. 和下载的资源有关
> 2. 可能是百度云账号被限制了，过一两天再试试

第一次使用没问题，后来就和上面说的情况一样了，瞬间完成任务，但是文件大小为0kb。等了两三天再试还是不行，是否有可能是因为账号被后台检测后做了记录？

**Comment by 88250** [comment]
@sdsy888 有可能。

**Comment by sdsy888** [comment]
那应该是了。。谢谢




| |
sdsy888@126.com
|
|
邮箱：sdsy888@126.com
|

Signature is customized by Netease Mail Master

在2019年04月19日 19:40，D 写道：

@sdsy888 有可能。
