### ISSUE TITLE
去掉黑客派登录并开源

### ISSUE THREAD

**Issue by 88250** [b3log/baidu-netdisk-downloaderx#19]
BND1 和 BND2 去掉黑客派登录并进行开源。

**Comment by nealkafuly** [comment]
牛逼，第二个版本的UI不错了，维护下去，估计有压力，百度啥时候封杀

**Comment by Vanessa219** [comment]
![bnd2](https://user-images.githubusercontent.com/970828/52894072-df473f80-31de-11e9-8301-33d2fa9858b4.png)

**Comment by 88250** [comment]
@nealkafuly BND 不是一个*正常*开源项目的方向，选择开源仅仅是为了交流代码。以后维护可能会很少了。
