### ISSUE TITLE
能出个 docker 版么

### ISSUE THREAD

**Issue by ash0080** [b3log/baidu-netdisk-downloaderx#2]
方便

**Comment by 88250** [comment]
桌面 GUI 程序双击运行已经很方便了，另外，做成 docker image 肯定比这大不少。

**Comment by lanybass** [comment]
代码在哪里？
main.go?

**Comment by 88250** [comment]
代码暂时不开源。

**Comment by 88250** [comment]
@ash0080 直接用 https://github.com/iikira/BaiduPCS-Go 这个吧，更适合你的场景。
