### ISSUE TITLE
启动空白

### ISSUE THREAD

**Issue by Vanessa219** [b3log/baidu-netdisk-downloaderx#21]

**Comment by qinyao** [comment]
一样。。

**Comment by itzhangdee** [comment]
1. 安装 golang、node 环境
2. 项目目录 $GOPATH/src/github.com/b3log/bnd2
3. Windows 执行 build.bat
4. Mac 在 electron 目录下执行 `npm install && npm run start && npm run dist`
5windows在electron 目录下命令运行  npm run start 
直接下载是用不了的，最好从源地址下载 D:\repository\baidu-netdisk-downloaderx\bnd2\electron\dist【你的安装目录】会生成BND2 Setup 2.0.0.exe 这个文件才可以

**Comment by qinyao** [comment]
> 1. 安装 golang、node 环境
> 2. 项目目录 $GOPATH/src/github.com/b3log/bnd2
> 3. Windows 执行 build.bat
> 4. Mac 在 electron 目录下执行 `npm install && npm run start && npm run dist`
>    5windows在electron 目录下命令运行  npm run start
>    直接下载是用不了的，最好从源地址下载 D:\repository\baidu-netdisk-downloaderx\bnd2\electron\dist【你的安装目录】会生成BND2 Setup 2.0.0.exe 这个文件才可以

当然是编译以后打开空白

**Comment by liov** [comment]
白屏。。。

**Comment by Vanessa219** [comment]
@liov 最新代码也不行？请具体描述一下重现步骤。

**Comment by sdsy888** [comment]
> @liov 最新代码也不行？请具体描述一下重现步骤。

mac端（最新mojave系统）编译完bnd2版本后，可以正常打开，但是点击查看全部文件时会白屏。
@Vanessa219

**Comment by HankelBao** [comment]
遇到相同问题。

**问题描述：**
* 左侧栏除了文件以外其他栏目可以正常切换
* 登录是的百度云网页可以正常显示，可以正常登录
* 只要从左侧栏点开文件或欢迎使用->查看所有文件都会导致白屏
* 点击切换正常没有反应要到重启BND2后才会要求重新登录

**重现步骤：**
1. git clone b3log/baidu-netdisk-downloaderx项目
2. 将bnd2复制到gopath相应地址：$GOPATH/src/github.com/b3log/bnd2
3. windows运行build.bat生成BND2 Setup 2.0.0.exe
4. 运行BND2 Setup 2.0.0.exe安装
5. 运行BND2

**解决尝试：**
试过重新编译/重新运行安装文件/重启/重新登录均没有解决问题

**Comment by Vanessa219** [comment]
![image](https://user-images.githubusercontent.com/970828/56214863-33608a00-6091-11e9-9844-1f9d8702539f.png)
@88250 
代码不是最新的，最新的应该是
```
saveFilePath: localStorage.saveFilePath || '',
```

**Comment by 88250** [comment]
已经部署最新代码。

PS 本地开发环境可以自己编译 React 部分，不然还是要走我们的服务器，我们服务器上不一定是最新代码。

**Comment by DD1ng-c** [comment]
最新的安装版登录账号后窗口内空白，请问如何解决（BND2.0WIndows）

**Comment by 88250** [comment]
> 最新的安装版登录账号后窗口内空白，请问如何解决（BND2.0WIndows）

我这里一切正常。可能是网络原因？
