### ISSUE TITLE
windows7 启动bat文件报错

### ISSUE THREAD

**Issue by wolfchinaliu** [b3log/baidu-netdisk-downloaderx#23]
在main.go 文件中的几个引用GitHub的连接都错了，不知道是写错了还是我需要配置什么东西？望告知，截图如下：
![image](https://user-images.githubusercontent.com/20653097/55126549-4e05aa00-5148-11e9-85e7-e85519e1eba2.png)

**Comment by 88250** [comment]
需要放到 $GOPATH/github.com/b3log/bnd2 路径下编译。

**Comment by liov** [comment]
白屏
