### ISSUE TITLE
不能正常下载

### ISSUE THREAD

**Issue by happyshrm** [b3log/baidu-netdisk-downloaderx#26]
### 描述问题
下载报错，具体信息可以看图片哈

### 期待的结果
可以正常下载

### 截屏或录像

![image](https://user-images.githubusercontent.com/20008685/60378168-18c36d80-9a51-11e9-9705-aba719851a33.png)

### 桌面端环境

- OS: mac
- Version [BND2.0]

**Comment by 88250** [comment]
可能是账号受限了，只能开通超级会员解决。

**Comment by happyshrm** [comment]
。。。。。。
