### ISSUE TITLE
提供可执行文件

### ISSUE THREAD

**Issue by 88250** [b3log/baidu-netdisk-downloaderx#29]
既然已经被其他人把可执行文件在互联网上公开了，那索性就在项目主页上提供了吧....

**Comment by 88250** [comment]
https://github.com/b3log/baidu-netdisk-downloaderx/releases

**Comment by chenwenshu** [comment]
BND1的Mac版解压之后没有后缀没办法执行
<img width="377" alt="image" src="https://user-images.githubusercontent.com/19535983/62018536-ab406380-b1ed-11e9-9509-39cafaa52556.png">

**Comment by 88250** [comment]
> BND1的Mac版解压之后没有后缀没办法执行
> <img alt="image" width="377" src="https://user-images.githubusercontent.com/19535983/62018536-ab406380-b1ed-11e9-9509-39cafaa52556.png">

赋一下执行权限，如果启动报错请重试。
