### ISSUE TITLE
BND2: 为客户端增加查看控制台的入口

### ISSUE THREAD

**Issue by antfu** [b3log/baidu-netdisk-downloaderx#31]
### 你在什么场景下需要该功能？

因为BND2是面向程序员使用的，使用户可以打开控制台可以方便发现问题，更利于社区贡献。

### 描述可能的解决方案

可以增加一个开发者分页，为客户端增加查看控制台的入口。

### 描述你认为的候选方案

或启用F12快捷键等。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by Vanessa219** [comment]
开发模式的话是可以 F12 的，如果需要了解细节可以下载源码进行调试。

**Comment by antfu** [comment]
像VSCode的Stable版也是可以开控制台的，个人认为这样有助于用户第一时间发现问题而不是重现编译测试版。

**Comment by 88250** [comment]
> 像VSCode的Stable版也是可以开控制台的，个人认为这样有助于用户第一时间发现问题而不是重现编译测试版。

我觉得也是，好像也不存在什么安全问题，开 F12 有助于用户更好地了解项目，出问题时也可以更方便地进行细节反馈。
