### ISSUE TITLE
挺好的，只不过偶尔下着下着突然速度变得很慢

### ISSUE THREAD

**Issue by 583175694** [b3log/baidu-netdisk-downloaderx#36]
![image](https://user-images.githubusercontent.com/26473617/61264046-a7f4b300-a7bd-11e9-82a6-dbb8d607599b.png)

![image](https://user-images.githubusercontent.com/26473617/61264042-a1fed200-a7bd-11e9-9b52-2bc749187994.png)

**Comment by 88250** [comment]
影响下载速度主要有 3 个原因：

1. 本地带宽
2. 资源本身是否是热点资源
3. 账号是否被限速

账号被限速的话下载速度会降到 10K 左右，所以看上去应该是资源本身的原因。当然，要加速也可以，开通百度网盘 SVIP 😂

**Comment by 583175694** [comment]
哈哈哈 Thx
