### ISSUE TITLE
可以提供文件搜索吗？

### ISSUE THREAD

**Issue by OiCkilL** [b3log/baidu-netdisk-downloaderx#38]
像 baidupcs-web 这个同样基于 baidupcs-go 的项目已经支持文件搜索和回收站管理功能，期望本项目也可以加入

**Comment by 88250** [comment]
暂时没有计划加入文件管理类功能，这类功能建议用官方网盘客户端，BND 仅作为加速下载使用，保持简洁。

感谢反馈 😄
