### ISSUE TITLE
好像还是限速了

### ISSUE THREAD

**Issue by weipoint** [b3log/baidu-netdisk-downloaderx#39]
目前用的是bnd2版本，昨天晚上试用速度确实很快，能达到几兆，但是今天不行了，今天就直接都是100以内了，就跟用百度云盘下载一个德行了，是被百度针对了吗？
<img width="953" alt="WX20190719-223952@2x" src="https://user-images.githubusercontent.com/745355/61544192-832b6480-aa77-11e9-959a-ddce699975c7.png">

**Comment by 88250** [comment]
https://hacpai.com/article/1563154719934/comment/1563248827088?r=88250

**Comment by weipoint** [comment]
对的，我就是在码云下载的安装包，确实限速了

**Comment by 88250** [comment]
这没办法的，是百度在服务端限速账号。只能等 CD 或者开通 SVIP。

**Comment by frozamilan1899** [comment]
@88250  我在码云上下载的bnd2-v2.0.0程序，登录下载最高到了12M/s，很快，感谢！

**Comment by HOLL4ND** [comment]
我第一次下载的时候很快，后面的下载都是和百度一样的速度了

**Comment by xueji123** [comment]
第一次下载速度很快，之后下载就是几十k每秒，跟百度网盘一样

**Comment by weipoint** [comment]
一次别下那么多文件，一次下载一个文件好像还好

**Comment by chaotianjiao** [comment]
![image](https://user-images.githubusercontent.com/42534375/62126880-4a0ab400-b303-11e9-965f-d3473ae661c2.png)
还是限速了，我的第一次用
