### ISSUE TITLE
谢谢作者！请问会被封号吗？

### ISSUE THREAD

**Issue by 405028157** [b3log/baidu-netdisk-downloaderx#40]
请问大佬这个不限速下载在机制上可以避免被封号吗？在网上有一些关于封号的消息，下面是几个例子
[百度网盘又在封号了！原因很无奈！ 
](https://www.sohu.com/a/218384122_681523)
[百度云新机制，无缘无故被封号的人都进来看一下
](http://tieba.baidu.com/p/6064946293)
[百度网盘大规模封号！这种操作千万别碰！
](https://baijiahao.baidu.com/s?id=1590018870637436851&wfr=spider&for=pc)

**Comment by 88250** [comment]
目前暂时没有用户反馈账号被封，但是使用频繁的话账号会被限速，这一点是确定的。
