### ISSUE TITLE
打开BND2报错

### ISSUE THREAD

**Issue by yhc1990518** [b3log/baidu-netdisk-downloaderx#41]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题
build后打开BND2直接报错，说文件存在

### 重现步骤
1. build
2. 安装
3. 打开bnd2.exe

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。
![image](https://user-images.githubusercontent.com/24221476/61588125-b16c8980-abc8-11e9-94cb-89517637619d.png)

### 桌面端环境

- OS: [Windows10 Pro]
- Browser [好像和浏览器没啥关系吧。。。]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息
无

**Comment by 88250** [comment]
请重启试试。

**Comment by yhc1990518** [comment]
似乎还是不行，我使用了管理员模式打开执行程序也是一样的。
![image](https://user-images.githubusercontent.com/24221476/61588207-fcd36780-abc9-11e9-9dce-15ecbc30f76f.png)
进入以后可以做一些操作，但是和浏览器内效果是一样的。上面红圈标准的东西一直不会消失。使用开发工具查看有多个js错误，大部分都是找不到js文件。
![image](https://user-images.githubusercontent.com/24221476/61588223-2c826f80-abca-11e9-8159-ccf4879ea280.png)

**Comment by 88250** [comment]
哦，看上去你应该是自己编译的吧？

可以看下 home 下面的 .bnd2 目录中目前有哪些文件。

**Comment by Vanessa219** [comment]
把 .bnd2 删了，重启看看

**Comment by yhc1990518** [comment]
好了  好像是编译的时候golang下载依赖有失败的  我重新弄了一次就好了。
不好意思

**Comment by 88250** [comment]
编译脚本可能需要改进，报错情况下应该退出。如果有可能可以帮忙完善一下，谢谢 🙏

**Comment by zackertypical** [comment]
请问是怎么解决的呢,我也是这个问题,编译的时候就报错了

**Comment by 88250** [comment]
> 请问是怎么解决的呢,我也是这个问题,编译的时候就报错了

有什么报错？
