### ISSUE TITLE
mac下bnd1第一次打开正常，第二次之后打开就一直报错

### ISSUE THREAD

**Issue by SangoYu** [b3log/baidu-netdisk-downloaderx#44]
2019-07-23 22:46:59.967 bnd[864:9310] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1575.12/Foundation/Misc.subproj/NSUndoManager.m:361
2019-07-23 22:46:59.967 bnd[864:9310] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2ca77cfd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5711da17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2ca92a1a +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff2ed31c85 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x00007fff2ec64cfa +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 473
	5   AppKit                              0x00007fff2a03f915 -[NSApplication run] + 916
	6   bnd                                 0x00000000043f919b uiMain + 43
	7   bnd                                 0x0000000004056ba0 runtime.asmcgocall + 112
)
libc++abi.dylib: terminating with uncaught exception of type NSException
SIGABRT: abort
PC=0x7fff58a262c6 m=6 sigcode=0
signal arrived during cgo execution

goroutine 22 [syscall, locked to thread]:
runtime.cgocall(0x43dc2a0, 0xc42004a780, 0xc420154168)
	/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc42004a750 sp=0xc42004a718 pc=0x4004354
github.com/b3log/bnd/vendor/github.com/andlabs/ui._Cfunc_uiMain()
	_cgo_gotypes.go:1784 +0x41 fp=0xc42004a780 sp=0xc42004a750 pc=0x40e4861
github.com/b3log/bnd/vendor/github.com/andlabs/ui.start(0xc4200a2180, 0x452faf8)
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/andlabs/ui/main.go:56 +0x10e fp=0xc42004a7d0 sp=0xc42004a780 pc=0x40e9c9e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42004a7d8 sp=0xc42004a7d0 pc=0x4057eb1
created by github.com/b3log/bnd/vendor/github.com/andlabs/ui.Main
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/andlabs/ui/main.go:36 +0x66

goroutine 1 [chan receive]:
github.com/b3log/bnd/vendor/github.com/andlabs/ui.Main(0x452faf8, 0xc420472a80, 0xc0)
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/andlabs/ui/main.go:37 +0x86
main.main()
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/main.go:78 +0x65

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa7
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 55 [sleep]:
time.Sleep(0x34630b8a000)
	/usr/local/go/src/runtime/time.go:102 +0x166
github.com/b3log/bnd/vendor/github.com/iikira/BaiduPCS-Go/pcscache.(*dirCache).GC.func1(0x4826e30)
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/iikira/BaiduPCS-Go/pcscache/dir_cache.go:58 +0x2f
created by github.com/b3log/bnd/vendor/github.com/iikira/BaiduPCS-Go/pcscache.(*dirCache).GC
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/iikira/BaiduPCS-Go/pcscache/dir_cache.go:56 +0x55

goroutine 56 [sleep]:
time.Sleep(0xdf8475800)
	/usr/local/go/src/runtime/time.go:102 +0x166
github.com/b3log/bnd/vendor/github.com/iikira/BaiduPCS-Go/requester.(*tcpAddrCache).GC.func1(0x4827ea0)
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/iikira/BaiduPCS-Go/requester/tcpaddr_cache.go:66 +0x2f
created by github.com/b3log/bnd/vendor/github.com/iikira/BaiduPCS-Go/requester.(*tcpAddrCache).GC
	/Users/Vanessa/Work/Code/GoGoGo/src/github.com/b3log/bnd/vendor/github.com/iikira/BaiduPCS-Go/requester/tcpaddr_cache.go:64 +0x55

goroutine 62 [IO wait]:
internal/poll.runtime_pollWait(0x6858ed8, 0x72, 0xc42034f9a8)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420199798, 0x72, 0xffffffffffffff00, 0x45675c0, 0x47d2110)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420199798, 0xc4205a6000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420199780, 0xc4205a6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc420199780, 0xc4205a6000, 0x1000, 0x1000, 0x4053f90, 0xc420000180, 0x4)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200c49a0, 0xc4205a6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
net/http.(*persistConn).Read(0xc420177320, 0xc4205a6000, 0x1000, 0x1000, 0xc42034fb98, 0x4006445, 0xc4205ca120)
	/usr/local/go/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc42013cd20)
	/usr/local/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc42013cd20, 0x1, 0x0, 0x0, 0x1, 0xc420555080, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc420177320)
	/usr/local/go/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1237 +0x95a

goroutine 63 [select]:
net/http.(*persistConn).writeLoop(0xc420177320)
	/usr/local/go/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1238 +0x97f

goroutine 85 [IO wait]:
internal/poll.runtime_pollWait(0x6858e08, 0x72, 0xc42005a9a8)
	/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc420199898, 0x72, 0xffffffffffffff00, 0x45675c0, 0x47d2110)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc420199898, 0xc4201c5000, 0x1000, 0x1000)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc420199880, 0xc4201c5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:157 +0x1dc
net.(*netFD).Read(0xc420199880, 0xc4201c5000, 0x1000, 0x1000, 0x4053f90, 0xc420000180, 0x4)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200c49f8, 0xc4201c5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:176 +0x6a
net/http.(*persistConn).Read(0xc4201777a0, 0xc4201c5000, 0x1000, 0x1000, 0xc42005ab98, 0x4006445, 0xc4200a2120)
	/usr/local/go/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc42013d320)
	/usr/local/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc42013d320, 0x1, 0x0, 0x0, 0x1, 0xc420555500, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc4201777a0)
	/usr/local/go/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1237 +0x95a

goroutine 86 [select]:
net/http.(*persistConn).writeLoop(0xc4201777a0)
	/usr/local/go/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1238 +0x97f

rax    0x0
rbx    0x700008b0d000
rcx    0x700008b0b4d8
rdx    0x0
rdi    0x2703
rsi    0x6
rbp    0x700008b0b510
rsp    0x700008b0b4d8
r8     0x700008b0b3a0
r9     0x700008b0b570
r10    0x0
r11    0x206
r12    0x2703
r13    0x3000000008
r14    0x6
r15    0x2d
rip    0x7fff58a262c6
rflags 0x206
cs     0x7
fs     0x0
gs     0x0

[进程已完成]

**Comment by 88250** [comment]
你好，这个 bug 确实存在且一直无法修复。请多次尝试重启。

**Comment by SangoYu** [comment]
好吧，多试了几次，果然好了 😂
