### ISSUE TITLE
断点续传&托盘化

### ISSUE THREAD

**Issue by shtu-cham** [b3log/baidu-netdisk-downloaderx#45]
当退出应用时，我希望下载进程能够被保留，而在重新加载应用后，可以继续上次未完成的下载。另外下载时希望BND2可以托盘化。

**Comment by 88250** [comment]
你好，暂时不准备做这方面的优化了，见谅。

**Comment by shtu-cham** [comment]
> 你好，暂时不准备做这方面的优化了，见谅。

能麻烦告知可能会有的新特性么？

**Comment by 88250** [comment]
功能特性方面不会增加了，尽量保持可用。
