### ISSUE TITLE
下载16G大文件异常

### ISSUE THREAD

**Issue by ikarosu** [b3log/baidu-netdisk-downloaderx#51]
### 描述问题

下载4个分卷压缩的资源报错，前3卷都是16G大小，
并不是一开始就错误，都能正常下载一段时间，其中002，003，004都异常，
最终剩001分卷在下载，永远显示大小0，0%，剩余68-80h，速度50k
猜测是无法下载大文件

### 桌面端环境

- OS: Windows 10 1903 build 18362.239
- Version BND2 v2.0.0

**Comment by 88250** [comment]
这个情况可能只能开通网盘 SVIP 了。
