### ISSUE TITLE
BND1 running error

### ISSUE THREAD

**Issue by cmmei** [b3log/baidu-netdisk-downloaderx#52]
在[黑客派](https://hacpai.com)没有找到相关的问题讨论。

----

### 描述问题

下载了 BND1 4.0.0 ，解压缩，双击运行，出错。重启打开还是如此。

### 截图

![bnd4-error](https://user-images.githubusercontent.com/11864255/61996333-bb5d2380-b0c5-11e9-84b4-a2cd61f731e2.png)

### 桌面端环境

Ubuntu 18.04

**Comment by 88250** [comment]
看上去可能是网络问题造成的，我这里目前重现不了哦。

**Comment by JohnRDoe** [comment]
确实是网络问题，我刚刚也出现了这个提示，然后换了流量热点之后发现可以了。
推测可能是网络被限制了

**Comment by 88250** [comment]
我关闭这个问题了，谢谢反馈。
