### ISSUE TITLE
BND2 根目录下不显示下载按钮

### ISSUE THREAD

**Issue by yuif37** [b3log/baidu-netdisk-downloaderx#53]
### 描述问题

打开全部文件，存储在根目录下的非文件夹文件在右侧没有下载按钮，将文件放在任意文件夹内，并打开文件夹，即可出现下载按钮。

### 重现步骤

请描述如何重现这个问题：

1. 打开「全部文件」
2. 找到任意一个文件
3. 右侧没有下载按钮

### 期待的结果

应当出现下载按钮

### 截屏或录像
https://f002.backblazeb2.com/file/Blog-Resources/Screen+Recording+2019-07-29+at+09.21.08.mov

### 桌面端环境

- OS: macOS 10.15 Beta (19A512f)
- Browser Chrome
- Version 75.0.3770.142 (Official Build) (64-bit)

### 其他信息
暂无

**Comment by 88250** [comment]
感谢反馈，稍后进行修复。
