### ISSUE TITLE
第一次登录后 下载的几个文件后 网速回归到限速状态 

### ISSUE THREAD

**Issue by desstiony** [b3log/baidu-netdisk-downloaderx#55]
win10 昨晚第一次尝试使用 ，下载速度很快 ，下载完几个文件后 ，网速回归限速状态。今天早上又进行尝试 依旧限速状态 。  
![image](https://user-images.githubusercontent.com/26624959/62174376-4e1eec00-b36c-11e9-8bb7-7b26805ec7ce.png)

**Comment by 88250** [comment]
谢谢反馈，这个没办法哦，请看 https://hacpai.com/article/1563154719934
