### ISSUE TITLE
MacOS BND2 v2.0.0 下载失败。

### ISSUE THREAD

**Issue by HuDaQian** [b3log/baidu-netdisk-downloaderx#57]
### 描述问题

下载失败。

### 重现步骤

请描述如何重现这个问题：

BND2 v2.0.0 下载失败。

### 截屏或录像
<img width="1007" alt="WeChate81b8d3f2a95582ace387e1576bcf7ba" src="https://user-images.githubusercontent.com/15866222/62205569-50ac3080-b3c2-11e9-949c-9e58c9b60ce8.png">

### 桌面端环境

- MacOS 
- BND2
- Mojave 10.14.6

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
如果方便的话请在官方客户端更新一下文件名，尽量改短些，然后再试试看是否 OK，谢谢。

**Comment by HuDaQian** [comment]
我更新了下仓库，重新build了下，然后重新登陆了，名字也改了，可是还是同样的问题。🤦‍♂️

**Comment by 88250** [comment]
把 ~/.bnd2 删了，然后重新安装试试。

**Comment by lipengyihao** [comment]
一登陆就这样啊
![image](https://user-images.githubusercontent.com/13689733/62798798-b9598280-bb11-11e9-9536-ca8947199b6f.png)

**Comment by 88250** [comment]
@lipengyihao 看上去是你本地的网络配置问题（比如 hosts 文件）导致，不是程序问题。

**Comment by EverettSy** [comment]
亲测，防火墙的问题，将防火墙关闭就OK了

**Comment by 88250** [comment]
先关闭 issue，如果还有问题请跟帖。
