### ISSUE TITLE
MacOS BND2 打开报错

### ISSUE THREAD

**Issue by flute** [b3log/baidu-netdisk-downloaderx#58]
### 描述问题

MacOS BND2 打开，登陆百度账号，点击全部，报错：

### 截屏

如果可能，请尽量附加截图或录像来描述你遇到的问题。
![image](https://user-images.githubusercontent.com/5842406/62261616-885dbb80-b448-11e9-89e8-1f3e8ee2fb8e.png)

### 桌面端环境

- OS: Mac
![image](https://user-images.githubusercontent.com/5842406/62261758-ee4a4300-b448-11e9-8203-0bf5d7e65be8.png)

- Browser Chrome
版本 75.0.3770.142（正式版本） （64 位）

- Version 
BND2-v2.0.0-mac.dmg

**Comment by 88250** [comment]
你好，请更换网络后重试。

**Comment by NANAyano** [comment]
我也是！换网络也不太行？
