### ISSUE TITLE
new feature request

### ISSUE THREAD

**Issue by rfyiamcool** [b3log/baidu-netdisk-downloaderx#6]
提几个我个人的小建议，望采纳 .

1. 每次重新下载的时候会导致重复下载.
2. 操作界面有些简陋

很赞的项目 ! 用了有段时间了, 没出过什么bug.

**Comment by 88250** [comment]
1. 已经下载过的应该不会重复下载，如果有重复下载那就是 bug 了，等有空看看
2. 有第二版的计划，考虑用 Electron 重写，支持多个下载任务同时进行

谢谢反馈，我们会继续努力了 😅
