### ISSUE TITLE
BND1部分文件下载后为0B大小

### ISSUE THREAD

**Issue by curiositer** [b3log/baidu-netdisk-downloaderx#63]
### 描述问题

下载文件时，有时候原文件在云盘中正常显示，但是下载下来的文件是0B

### 重现步骤

请描述如何重现这个问题：

1.使用BND1，正常登陆，选择文件夹，点击开始下载
2.下载一段时间后，查看下载的文件，部分是0B大小，从那个文件之后都是0B大小的，但是进度正常进行，没有显示错误。
3.点击0B的文件，也不能正常打开。
4.尝试关闭后再次下载，数据缓冲后仍然是0B大小。

### 期待的结果

文件能够正常下载，而不是全为0B大小。

### 截屏或录像

![image](https://user-images.githubusercontent.com/34828878/62539572-1510db00-b888-11e9-916d-3b26d5897330.png)

### 桌面端环境

- OS: windows 10
- Version BND1 v4.0.0

**Comment by jlszts** [comment]
这工具貌似不能用了

**Comment by 88250** [comment]
刚刚测试了下，我这里下载没有问题

![image](https://user-images.githubusercontent.com/873584/62546594-56a88280-b896-11e9-9c0c-298ae91e10e6.png)

你那里不行的话我估计是账号被限速了，只能开网盘会员或者等几天再试试。感谢两位反馈！

**Comment by 3056521761** [comment]
大文件（1G以上的就不要想了）

**Comment by mybrew** [comment]
我这边用了也是0字节，BND2能下载，但是速度很慢，只有50K不到，我是100M带宽。下载电影有2,3M/S的。这个速度还不如百度网盘下载，肯定不正常。

**Comment by 88250** [comment]
> 我这边用了也是0字节，BND2能下载，但是速度很慢，只有50K不到，我是100M带宽。下载电影有2,3M/S的。这个速度还不如百度网盘下载，肯定不正常。

如果经常下载的话，限速是无法避免的。

**Comment by xiaoshi1994** [comment]
我这边也是这个问题 ，怎么破？大佬想想办法 ，或者能让我们可以注册很多百度云账户吗？
