### ISSUE TITLE
BND2 V2.0.0 MAC 切换账号无响应

### ISSUE THREAD

**Issue by BlackFish-ops** [b3log/baidu-netdisk-downloaderx#64]
### 描述问题

BND2 V2.0.0 for MAC 切换账号无响应

### 重现步骤

1. Go to 'BND2 V2.0.0'
2. Click on '切换账号'
3. See error ‘无任何响应’

### 期待的结果

点击切换账号，弹出登陆账号、密码输入框。

### 截屏或录像

![未命名](https://user-images.githubusercontent.com/53802513/62671394-4cd36c00-b9c9-11e9-8a19-9c1fbe1a5b11.gif)
### 桌面端环境

- OS: [mac]
- Browser [chrome]
- Version [Mojave 10.14.6]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by Vanessa219** [comment]
请问你是自己编译的最新代码还是使用最新的安装包？

**Comment by BlackFish-ops** [comment]
使用的安装包

**Comment by Vanessa219** [comment]
你从官方下载一个最新的试一下

**Comment by BlackFish-ops** [comment]
@Vanessa219 ok

**Comment by BlackFish-ops** [comment]
奇怪，今天尝试了还是不行，先这样凑活用吧，谢谢。
