### ISSUE TITLE
BND1在第一次下载后，在家里的电脑再下载一次时，生成的文件全部0字节

### ISSUE THREAD

**Issue by liganbo** [b3log/baidu-netdisk-downloaderx#66]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

BND1在第一次下载后，在家里的电脑再下载一次时，生成的文件全部0字节

请尽量清晰精准地描述你碰到的问题。

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 桌面端环境

- OS: windows 10
- Browser ：chrome
- Version ：76.0.3809.100

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by QuentinChansey** [comment]
我也遇到同样的问题，点了下载之后一瞬间就下好了，然后ls -hl一看，还真是全部0字节，全部空的，为啥会这样呢

**Comment by 88250** [comment]
https://github.com/b3log/baidu-netdisk-downloaderx/issues/63
