### ISSUE TITLE
bnd2 windows build 时候因为go包下载出错导致最后生成的安装包报错

### ISSUE THREAD

**Issue by zjylx** [b3log/baidu-netdisk-downloaderx#67]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

windows下执行build.bat脚本之后，因为go语言包下载出错（网络原因），导致最后的安装包会出错。

### 重现步骤

请描述如何重现这个问题：
满足以下俩个条件
1. 没有goproxy代理
2. 无法连接到golang.org/x

最后执行build.bat

### 期待的结果

中间的go build会出错，但是整个打包还在继续，导致最后打包出来的程序报错。

### 桌面端环境

- OS: [windows]

###建议修改为：
`set GOPROXY=https://goproxy.io
echo Building Kernel
set GOOS=windows
set GOARCH=amd64
go version
go build -v -o electron/bnd2.exe -ldflags "-s -w -H=windowsgui
if "%errorlevel%" == "1" goto :errorend

set GOOS=darwin
set GOARCH=amd64
go build -v -o electron/bnd2 -ldflags "-s -w"
if "%errorlevel%" == "1" goto :errorend

echo Building UI
cd electron
node -v
call npm -v
call npm install && npm run dist
cd ..

:errorend
echo "Error in go build"`

**Comment by 88250** [comment]
感谢帮忙修复 https://github.com/b3log/baidu-netdisk-downloaderx/pull/68
