### ISSUE TITLE
无法拉取依赖包

### ISSUE THREAD

**Issue by liangzhaoliang95** [b3log/baidu-netdisk-downloaderx#69]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

github.com/b3log/bnd2 (download)
# cd .; git clone https://github.com/b3log/bnd2 E:\personal_project\baidu-netdisk-downloaderx\src\github.com\b3log\bnd2
Cloning into 'E:\personal_project\baidu-netdisk-downloaderx\src\github.com\b3log\bnd2'...
remote: Repository not found.
fatal: repository 'https://github.com/b3log/bnd2/' not found
package github.com/b3log/bnd2/command/...: exit status 128

**Comment by 88250** [comment]
你好，这是你网络或者 git 配置的问题。
