### ISSUE TITLE
BND2 计划

### ISSUE THREAD

**Issue by 88250** [b3log/baidu-netdisk-downloaderx#7]
1. 完全重写
2. 改进登录方式
2. 支持多任务下载
3. 支持任务暂停

大家如果需要 BND2 请给该 issue 点赞，超过 50 赞我们就开工~

----

### 20180808 

感谢大家参与投票，目前已经集满 50 赞，我们已经开始动手实现，预计 9 月份 BND2 会发布第一个版本！以后每隔两天打个卡发下进度，直到发布。

### 20180810 

设计全新的“混合架构”（客户端框架+前后端分离+下载器内核），使用 Electron、React、golang 进行实现。

### 20180812

框架部分基本完成，主要是自动更新、前后端交互机制。前端部分完成账号登录集成，下载列表框架；后端部分完成列出网盘文件、提取下载链接。

### 20180814

主界面和下载功能基本完成，还需要继续细化下载列表、完成列表的管理，比如暂停/恢复/移除。计划在发布测试阶段不消耗积分，鼓励大家帮忙参与测试。

### 20180816

仪表盘

![image](https://user-images.githubusercontent.com/873584/44193934-1c1a7700-a167-11e8-86d0-505f728f6794.png)

文件浏览

![image](https://user-images.githubusercontent.com/873584/44162645-7d086780-a0f3-11e8-8041-68c19570b59c.png)

下载列表

![image](https://user-images.githubusercontent.com/873584/44162406-cc01cd00-a0f2-11e8-802a-35a071322dd4.png)

搞的差不多了，还有一些细节需要再调整。预计周末会发布 BND2 v1.0.0，大家可以帮忙来测试了！

### 20180817

**Mac 和 Windows 版已经发布，下载地址 https://share.weiyun.com/5Z32JP8**

**Comment by wujunze** [comment]
不开源吗?

**Comment by 88250** [comment]
@wujunze 嗯，不开源

**Comment by 1556837534** [comment]
期待下

**Comment by 88250** [comment]
@1556837534 谢谢支持！

**Comment by Coderzgh** [comment]
希望改进Mac和Linux客户端下载路径不能自定义的问题啦，哈哈

**Comment by 88250** [comment]
@Coderzgh 收到，BND2 会支持设置下载任务保持路径的 😸

**Comment by digglife** [comment]
支持支持，希望能给 Mac 版画个图标吧，哈哈哈哈。

**Comment by 88250** [comment]
@digglife 会有的，这次绝不偷懒 😊

**Comment by yanxiangrui** [comment]
支持

**Comment by 99103248** [comment]
前排支持

**Comment by Hodpel** [comment]
单位流量调低一点吧..
有时候下点不大不小的文件或者多文件的时候积分被吃的受不了
特别是现在10积分/G
之前下载10m的文件直接吃了10积分
可以尝试  某大小以下的文件扣固定积分
比如200M以内文件统一扣2 积分
之类的

**Comment by 88250** [comment]
@Hodpel 好的，这一版实现的时候考虑一下。

**Comment by vinasis** [comment]
给点积分吧

**Comment by gitors** [comment]
这个百度会不会找你麻烦？

**Comment by 88250** [comment]
@gitors 没几个人用应该不会，找了的话就..

**Comment by Vampire1122** [comment]
D大，弄个记住密码吧

**Comment by Vampire1122** [comment]
还有流量那个，我觉得楼上的想法很好，设置一个文件大小梯度，每个梯度扣多少分/个文件，这样可能合理一些。

**Comment by 88250** [comment]
@Vampire1122 嗯，默认记住登录了，积分的话可能前期就不扣了，鼓励大家来使用测试。

**Comment by Vampire1122** [comment]
@88250 可以的！

**Comment by blueiou** [comment]
帮忙测试送积分吗 嘻嘻

**Comment by 88250** [comment]
@blueiou 测试阶段不消耗积分..

**Comment by hsm623** [comment]
大陆这边都是封锁账号联动ip的~ 
你确定你的软件能绕过这样的封锁/

**Comment by 88250** [comment]
@hsm623 目前暂时没人反馈封锁账号的问题；我也不确定我的软件能不能绕过这样的封锁 😂

**Comment by fanhanjie** [comment]
支持支持

**Comment by 88250** [comment]
@blueiou 账号只要不是被限速 10K 的话可以跑满带宽，被限速 10K 的话下载比较大的文件可以在 2M 左右，小文件大概在几百 K。

**Comment by Hodpel** [comment]
怎么加入测试...

**Comment by 88250** [comment]
@Hodpel 明天我会在社区发个帖子，留意一下 ✔️

**Comment by 88250** [comment]
## Mac 和 Windows 版已经发布，下载地址 https://share.weiyun.com/5Z32JP8

**Comment by Hodpel** [comment]
哇尴尬系统是32位的😭

**Comment by EvilCodes** [comment]
D哥你觉得写代码和看代码看书籍哪个更重要呢？

**Comment by gitors** [comment]
看代码看书籍 是为了什么？如果是为了好玩 那就看代码看书籍重要，如果还是为了写代码，那就……

**Comment by JianYu97** [comment]
删除文件这些功能后续可以考虑吗，有时候想删除的时候才发现没这个功能

**Comment by 88250** [comment]
@JianYu97 不做网盘文件管理相关功能。

**Comment by JianYu97** [comment]
了解

D <notifications@github.com> 于2018年9月29日周六 下午2:44写道：

**Comment by JianYu97** [comment]
> @JianYu97不做网盘文件管理相关功能。

了解

**Comment by zhuxiaoxi** [comment]
BND2能不能放到Github单一个仓库发布，我知道2是闭源的。那个微云下了10分钟都没下载下来，速度太慢了。

**Comment by 88250** [comment]
@zhuxiaoxi 已经上传。

**Comment by ACG-Q** [comment]
> BND2能不能放到Github单一个仓库发布，我知道2是闭源的。那个微云下了10分钟都没下载下来，速度太慢了。

用idm下载呗
