### ISSUE TITLE
无论是网页还是直接搜索bnd2都没有

### ISSUE THREAD

**Issue by liangzhaoliang95** [b3log/baidu-netdisk-downloaderx#70]
![QQ截图20190815170118](https://user-images.githubusercontent.com/34703350/63084982-06f54580-bf7f-11e9-92be-1e4ad0832675.png)
![QQ截图20190815170551](https://user-images.githubusercontent.com/34703350/63084983-078ddc00-bf7f-11e9-84a6-5a57a73012b6.png)

**Comment by 88250** [comment]
bnd 和 bnd2 都在这个仓库里了，你可能是没有启用 go module 吧。
