### ISSUE TITLE
English Please

### ISSUE THREAD

**Issue by hobolance** [b3log/baidu-netdisk-downloaderx#71]
### What is the problem with Chinese README's

Firstly, we congratulate you for getting so much star by sharing this repository with humanity.

But it is very disappointing for non-Chinese speakers when one couldn't understand what a trending repository is about.

When we see such a repo on trending, our minds are blurring like Gollum's.

![Gollum Image](https://media.giphy.com/media/V4uGHRgz0zi6Y/giphy-downsized-large.gif)

There is a way **you can help** to solve this disappointment which I believe is experienced by many people who want to know more about your valuable work and appreciate it.

### What we want:
 - Please add English translation of your README so you are sharing your work and knowledge with more people.

### How this will help you:
 - More feedback to fix and improve your project.
 - New ideas about your project.
 - Greater fame.
 - ![SungerBob Image](https://media.giphy.com/media/3o7absbD7PbTFQa0c8/source.gif)

---

_“Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something.”_

_**— Richard Stallman**_

**Thank you!**	

> The developers of repo will not be held responsible for problems that arise in this script.

> This issue generated by [us/english-please](github.com/us/english-please) script. Please open issue on any error. Thank you!

**Comment by Lee981265** [comment]
> ### What is the problem with Chinese README's
> Firstly, we congratulate you for getting so much star by sharing this repository with humanity.
> 
> But it is very disappointing for non-Chinese speakers when one couldn't understand what a trending repository is about.
> 
> When we see such a repo on trending, our minds are blurring like Gollum's.
> 
> ![Gollum Image](https://camo.githubusercontent.com/cdb7f2c558a80c164262a967b1f5fcba657ad3ca/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f563475474852677a307a6936592f67697068792d646f776e73697a65642d6c617267652e676966)
> 
> There is a way **you can help** to solve this disappointment which I believe is experienced by many people who want to know more about your valuable work and appreciate it.
> 
> ### What we want:
> * Please add English translation of your README so you are sharing your work and knowledge with more people.
> 
> ### How this will help you:
> * More feedback to fix and improve your project.
> * New ideas about your project.
> * Greater fame.
> * ![SungerBob Image](https://camo.githubusercontent.com/0fd9023609acaf83957dbc4698fbdc1959cdc66c/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f376162736244375062544651613063382f736f757263652e676966)
> 
> _“Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something.”_
> 
> _**— Richard Stallman**_
> 
> **Thank you!**
> 
> > The developers of repo will not be held responsible for problems that arise in this script.
> 
> > This issue generated by [us/english-please](github.com/us/english-please) script. Please open issue on any error. Thank you!



Browser with Translation

**Comment by 88250** [comment]
我觉得中文蛮好的，中文也更适合该项目，谢谢你的建议。

**Comment by 88250** [comment]
[我为什么要用中文写项目文档](https://hacpai.com/article/1566191673842)。
