### ISSUE TITLE
希望增加docker 版本的

### ISSUE THREAD

**Issue by pbwind** [b3log/baidu-netdisk-downloaderx#72]
### 你在什么场景下需要该功能？
群晖NAS下使用，

### 描述可能的解决方案

制作docker版本，方便安装、使用

### 描述你认为的候选方案

docker版本的bnd

### 其他信息

-

**Comment by 88250** [comment]
你好，这个场景可以考虑使用 https://github.com/iikira/BaiduPCS-Go 进行替代。
