### ISSUE TITLE
go module依赖问题

### ISSUE THREAD

**Issue by runc** [b3log/baidu-netdisk-downloaderx#73]
![image](https://user-images.githubusercontent.com/1925916/63316209-c4e25000-c340-11e9-99f5-aeaf0afbb538.png)
![image](https://user-images.githubusercontent.com/1925916/63316227-cdd32180-c340-11e9-9769-6f64161b4253.png)

![image](https://user-images.githubusercontent.com/1925916/63316193-b09e5300-c340-11e9-987b-5dfba371e773.png)

第三张图中的依赖找不到，我看正确的路径是带了baidu-netdisk-downloaderx目录的，是不是go mod工具可以改变依赖路径，这个问题如何解决呢，还是从go mod中去寻找答案？

**Comment by 88250** [comment]
配置好 go module 的话就不用了 GOPATH 和项目目录对应了。

**Comment by runc** [comment]
绝非一个伸手党，以上回复太敷衍，这里把正确步骤贴出来：
go module 可以解决go path 多项目依赖的泥潭，其实我上面的截图可以看出我的go mod都配置好了，只所以还报错，是goland ide本身的报错，开启go mod集成就可以了，
![image](https://user-images.githubusercontent.com/1925916/63317313-f0ffd000-c344-11e9-9f95-9d0022250357.png)

同时贴一篇go mod文章加强理解：
https://roberto.selbach.ca/intro-to-go-modules/

**Comment by 88250** [comment]
> 以上回复太敷衍

从你的截图能看出什么来？能看出你用的是 Goland？？

你提问方式有问题：

* 没按照预设的 issue 模板进行问题描述，这个模板的目的就是为了方便排查
* go module 是 BND 编译的前提，没有人有义务为你科普

如何在开源社区提问可参考如下两篇分享：

* [《《提问的智慧》精读注解版》](https://hacpai.com/article/1536377163156)
* [《开源社区之提问的智慧》](https://hacpai.com/article/1544408700521)

**Comment by 2501224066** [comment]
打一架
