### ISSUE TITLE
建议作者把软件的名字改掉，否者就有标题党和欺骗的嫌疑了。

### ISSUE THREAD

**Issue by wuxiongwei** [b3log/baidu-netdisk-downloaderx#76]
建议作者把软件的名字改掉，否者就有标题党和欺诈的嫌疑了。
因为我看了80%issue中，都存在并提到没有不限速的效果，我自己亲身体验后也是一样。
另外软件内要求登陆百度网盘账号，更加加大了欺诈的嫌疑。

**Comment by 88250** [comment]
软件名字 BND 欺诈你啥了？

**Comment by MatrixLau** [comment]
首先，标题并没有提到有没有限速得问题，因为项目标题是baidu-netdisk-downloaderx，其次文中没有表明成功率百分之100，而且软件内部得登录百度云，你可以自己查看一下端口，是不是官方的，别现在啥都没有就这么有攻击性得说欺诈嫌疑，而且这是一个公开的仓库，没有收你的钱。
发送自 Windows 10 版邮件应用

发件人: wuxiongwei
发送时间: 2019年8月21日 21:27
收件人: b3log/baidu-netdisk-downloaderx
抄送: Subscribed
主题: [b3log/baidu-netdisk-downloaderx]=?UTF-8?Q?_=E5=BB=BA=E8=AE=AE=E4=BD=9C=E8=80=85=E6=8A=8A=E8=BD=AF=E4=BB=B6=E7=9A=84=E5=90=8D=E5=AD=97=E6=94=B9=E6=8E=89=EF=BC=8C=E5=90=A6=E8=80=85=E5=B0=B1=E6=9C=89=E6=A0=87=E9=A2=98=E5=85=9A=E5=92=8C=E6=AC=BA=E9=AA=97=E7=9A=84=E5=AB=8C=E7=96=91=E4=BA=86=E3=80=82?==?UTF-8?Q?_=28#76=29?=

建议作者把软件的名字改掉，否者就有标题党和欺诈的嫌疑了。
因为我看了80%issue中，都存在并提到没有不限速的效果，我自己亲身体验后也是一样。
另外软件内要求登陆百度网盘账号，更加加大了欺诈的嫌疑。

**Comment by JinJianh** [comment]
> 建议作者把软件的名字改掉，否者就有标题党和欺诈的嫌疑了。
> 因为我看了80%issue中，都存在并提到没有不限速的效果，我自己亲身体验后也是一样。
> 另外软件内要求登陆百度网盘账号，更加加大了欺诈的嫌疑。

1. 也没人说能100%成功啊，你没成功并不代表别人也没成功，而且成功了的会来提锤子个issue
2. 欺诈你啥了，又没收你钱，需要百度账号你觉得存在欺诈问题那你就别用呗(而且源码摆在那儿，有没有欺诈自己不会判断吗)

爱用用，不用拉倒

**Comment by wuxiongwei** [comment]
可能是我表达的不好，建议把“不限速”字眼去除。
