### ISSUE TITLE
mac BND2 打开报错

### ISSUE THREAD

**Issue by 652028815** [b3log/baidu-netdisk-downloaderx#77]
statistic.go:100:get global stat failed[Post http://localhost:6805/jsonrpc:dial tcp:lookup localhost:no  such host

**Comment by 88250** [comment]
看上去是本地的网络设置有问题。

**Comment by NANAyano** [comment]
我也是这样，求解！！！

**Comment by Changxysuf** [comment]
https://www.jianshu.com/p/33e755d5360e
