### ISSUE TITLE
百度账号被限

### ISSUE THREAD

**Issue by carlos9310** [b3log/baidu-netdisk-downloaderx#78]
### 你在什么场景下需要该功能？

本人百度账号被限速了。。。

### 描述可能的解决方案

百度账号虚拟化/代理

### 描述你认为的候选方案

百度账号虚拟化/代理

### 其他信息

百度账号虚拟化/代理

**Comment by 88250** [comment]
能稍微详细的描述一下“百度账号虚拟化/代理”是什么意思吗？

**Comment by carlos9310** [comment]
> 能稍微详细的描述一下“百度账号虚拟化/代理”是什么意思吗？

具体实现我不清楚。。就是想让bnd在百度账号限速的情况下也支持不限速下载，期待中。。

**Comment by 88250** [comment]
这恐怕违反自然原理了，实现不了啊 😂 
只能小号或者充值了。
