### ISSUE TITLE
下载与关闭问题

### ISSUE THREAD

**Issue by suyuanlin** [b3log/baidu-netdisk-downloaderx#80]
### 描述问题

将关闭按钮默认设置为后台运行，因为一旦关闭后，下载程序就断了，而且重启后没有记忆功能，下载后没完成的文件，不能导入再次下载，需要重新建立任务下载，耗时得很。
### 重现步骤
1.登录云盘，点击文件夹开始下载，里面有大概5个视频
2.下载到30%左右吧，由于任务切换，意外关闭了bnd2
3.再次打开，下载任务中没有任务了，将aria2文件直接拖到dnd2中无法识别继续下载，智能播放

### 期待的结果
可继续下载

**Comment by 88250** [comment]
感谢反馈，这个问题暂时没时间改进。目前不支持任务保存，只能重新选择需要下载的文件，数据会自动断点续传。
