### ISSUE TITLE
Windows 运行bnd2报错

### ISSUE THREAD

**Issue by t6am3** [b3log/baidu-netdisk-downloaderx#82]
### 描述问题
拉了最新源码编译安装后，运行bnd2报错, 具体报错如下

#### A JavaScript error occurred in the main process  
*Uncaught Exception:*  
Error: ENOENT, bnd2.exe not found in   
C:\Users\my_user_account\AppData\Local\Programs\bnd2-electron\resources\app.asar  
at createError(electron/js2c/asar.js:126:17)
……

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'
> 实际上只是运行就报错了

### 期待的结果

希望能

### 截屏或录像

![image.png](https://i.loli.net/2019/09/03/uVSdqIYpKFAkcJD.png)

### 桌面端环境

- OS: Windows 10 (64bit)
- Browser: chrome  76.0.3809.132(64bit)

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
请按照 README 里面的编译步骤进行。

**Comment by t6am3** [comment]
> 请按照 README 里面的编译步骤进行。

你好 我的确是按照md里的步骤来的啊
