### ISSUE TITLE
BND1 linux下下载到空文件

### ISSUE THREAD

**Issue by kulongwangzhi85** [b3log/baidu-netdisk-downloaderx#83]
### 描述问题

BND1 4.0.0版,在ubuntu18.04.下载到空文件,所有文件都是空的.

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [linux]
- Browser [chrome]
- Version 4.0.0

### 其他信息

无

**Comment by 88250** [comment]
https://github.com/b3log/baidu-netdisk-downloaderx/issues/81
