### ISSUE TITLE
改进与Bug

### ISSUE THREAD

**Issue by RealKiro** [b3log/baidu-netdisk-downloaderx#85]
BND2:
1. 没有暂停键 （有的时候某个文件下载出错需要暂停重新开始下，没有暂停键）
2. 无法在 断开/关闭/暂停 后在原来的下载位置继续下载 ，而是要从头开始下载对于大文件很麻烦；且文件持续下载若干时间后无速度，重启后下载的进度统统又没了又得去文件目录找文件重新下。

---
运行环境：Mac

**Comment by 88250** [comment]
https://github.com/b3log/baidu-netdisk-downloaderx/issues/65
