### ISSUE TITLE
闲鱼有人拿来卖钱

### ISSUE THREAD

**Issue by lupohan44** [b3log/baidu-netdisk-downloaderx#86]
https://market.m.taobao.com/app/idleFish-F2e/widle-taobao-rax/page-detail?wh_weex=true&wx_navbar_transparent=true&id=601330072073&ut_sk=1.ABzJxrcLK1IDAHlUZ0%252Bbe%252F7s_21407387_1568975708878.Copy.detail.601330072073.434232169&forceFlush=1

**Comment by 88250** [comment]
感谢告知。但是没法子，我也阻止不了 😂
