### ISSUE TITLE
【下载不成功】今天下载文件，本地创建了一个0字节的文件，然后提示下载完成

### ISSUE THREAD

**Issue by jimywu19** [b3log/baidu-netdisk-downloaderx#87]
可以正常登录，可以刷新查看文件列表，点击开始下载，提示正在缓冲，几秒钟提示下载完成。
本地只有0字节的文件，是百度网盘改变规则了吗？

**Comment by 88250** [comment]
https://hacpai.com/article/1563154719934 请参考回帖列表。
