### ISSUE TITLE
Bug:BND下载完成文件为0K

### ISSUE THREAD

**Issue by RealKiro** [b3log/baidu-netdisk-downloaderx#91]
1. 只能同时下载一个文件，若同时再开始另外一个文件下载就会闪退
2. 文件下载文件会显示0KB且显示下载完成

![image](https://user-images.githubusercontent.com/33367701/65871770-b19bb900-e3b1-11e9-8968-3fc32f7e3d12.png)

![image](https://user-images.githubusercontent.com/33367701/65871725-93ce5400-e3b1-11e9-9cb6-aee9230a1854.png)

**Comment by 88250** [comment]
https://hacpai.com/article/1563154719934 请参考回帖列表。
